# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/breeze-icons': 'Frameworks/6.24'
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kdoctools': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kiconthemes': 'Frameworks/6.24'
    'frameworks/knewstuff': 'Frameworks/6.24'
    'frameworks/ktexteditor': 'Frameworks/6.24'
    'frameworks/kuserfeedback': 'Frameworks/6.24'
    'third-party/qtkeychain': '@latest'

Options:
  test-before-installing: True
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
