# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6', 'macOS/Qt6']
  'require':
    'frameworks/breeze-icons': '@latest-kf6'
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/knewstuff': '@latest-kf6'
    'frameworks/ktexteditor': '@latest-kf6'
    'frameworks/ktextwidgets': '@latest-kf6'
    'frameworks/kuserfeedback': '@latest-kf6'
- 'on': ['Linux']
  'require':
    'sdk/selenium-webdriver-at-spi': '@latest-kf6'

Options:
  run-tests: True
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows' ]

