# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/ktextwidgets': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/ktexteditor': '@stable'
    'frameworks/knewstuff': '@stable'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/kactivities': '@stable'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows' ]
