# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/breeze-icons': '@latest-kf6'
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/knewstuff': '@latest-kf6'
    'frameworks/ktexteditor': '@latest-kf6'
    'frameworks/kuserfeedback': '@latest-kf6'
    'third-party/qtkeychain': '@latest'

Options:
  test-before-installing: True
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
  cmake-options: '-DWARNINGS_AS_ERRORS=ON'
