#ifndef KATE_CONFIG_H
#define KATE_CONFIG_H

/* config.h. Generated by cmake from config.h.cmake */

static const int KateVersionMajor = ${KATE_VERSION_MAJOR};
static const int KateVersionMinor = ${KATE_VERSION_MINOR};
static const int KateVersionMicro = ${KATE_VERSION_MICRO};

static const float KateVersion = ${KATE_VERSION_MAJOR}.${KATE_VERSION_MINOR};

#define KATE_VERSION "${KATE_VERSION}"

#cmakedefine HAVE_FDATASYNC 1
#cmakedefine HAVE_CTERMID 1
#cmakedefine KActivities_FOUND 1

#endif
