#ifndef KATE_CONFIG_H
#define KATE_CONFIG_H

/* config.h. Generated by cmake from config.h.cmake */

#define KATE_VERSION "${KDE_APPLICATIONS_VERSION}"

#cmakedefine HAVE_CTERMID 1
#cmakedefine KActivities_FOUND 1

#endif
