---
name: kate
confinement: classic
grade: stable
base: core24
adopt-info: kate
apps:
  kate:
    command: usr/bin/kate
    common-id: org.kde.kate.desktop
    desktop: usr/share/applications/org.kde.kate.desktop
assumes:
  - snapd2.58.3
compression: lzo
environment:
  QTWEBENGINEPROCESS_PATH: "$SNAP/usr/lib/qt6/libexec/QtWebEngineProcess"
  LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio:$SNAP/usr/lib${LD_LIBRARY_PATH}
  XDG_DATA_DIRS: "$XDG_DATA_DIRS:$SNAP/usr/share"
  XDG_CONFIG_DIRS: "$XDG_CONFIG_DIRS:$SNAP/etc/xdg"
  __EGL_VENDOR_LIBRARY_DIRS: "$SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d"
  LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/${CRAFT_ARCH_TRIPLET}/dri"
  QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins
layout:
  /usr/share/X11:
    symlink: $SNAP/usr/share/X11
  /usr/share/qt6:
    bind: $SNAP/usr/share/qt6
package-repositories:
  - type: apt
    components:
      - main
    suites:
      - noble
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
  mesa-patchelf:
    plugin: nil
    build-attributes:
      - enable-patchelf
    stage-packages:
      - libgl1-mesa-dri
      - libglut3.12
      - libglu1-mesa
      - patchelf
    stage:
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri"
  mesa-no-patchelf:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
    build-attributes:
      - no-patchelf
    stage:
      - usr/lib/${CRAFT_ARCH_TRIPLET}/dri
  qtconf:
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      cat <<EOF > $CRAFT_PART_INSTALL/usr/bin/qt.conf
      [Paths]
      Prefix = ../../
      LibraryExecutables = usr/lib/$CRAFT_ARCH_TRIPLET/qt6/libexec
      Plugins = usr/lib/$CRAFT_ARCH_TRIPLET/qt6/plugins
      Qml2Imports = usr/lib/$CRAFT_ARCH_TRIPLET/qt6/qml
      Translations = usr/share/qt6/translations
      Data = usr/share/qt6
      EOF
  kate:
    after:
      - mesa-patchelf
      - mesa-no-patchelf
      - qtconf
    parse-info:
      - usr/share/metainfo/org.kde.kate.appdata.xml
    plugin: cmake
    build-packages:
      - gettext
      - doxygen
      - graphviz
      - libxml2-utils
      - docbook-xml
      - docbook-xsl
      - libxkbcommon-dev
      - cmake
      - kf6-extra-cmake-modules
      - kf6-kconfig-dev
      - kf6-kcrash-dev
      - kf6-kdbusaddons-dev
      - kf6-kcolorscheme-dev
      - kf6-kdoctools-dev
      - kf6-kguiaddons-dev
      - kf6-ki18n-dev
      - kf6-kiconthemes-dev
      - kf6-kitemmodels-dev
      - kf6-kjobwidgets-dev
      - kf6-kio-dev
      - kf6-knewstuff-dev
      - kf6-kparts-dev
      - kf6-kpty-dev
      - kf6-syntax-highlighting-dev
      - kf6-ktexteditor-dev
      - kf6-threadweaver-dev
      - kf6-kwallet-dev
      - kf6-kwindowsystem-dev
      - kf6-kuserfeedback-dev
      - kf6-kxmlgui-dev
      - libplasma-dev
      - pkgconf
      - plasma-activities-dev
      - qt6-base-dev
      - libpulse0
      - python3
    stage-packages:
      - kf6-kdeclarative
      - kf6-ktexteditor
      - libaudio2
      - libpulse0
      - libplasma6
      - qt6-declarative
      - kf6-kbookmarks
      - kf6-kcolorscheme
      - kf6-kcompletion
      - kf6-kconfig
      - kf6-kconfigwidgets
      - kf6-kcoreaddons
      - kf6-kcrash
      - kf6-kdbusaddons
      - kf6-kguiaddons
      - kf6-ki18n
      - kf6-kiconthemes
      - kf6-kio
      - kf6-knewstuff
      - kf6-kparts
      - kf6-kservice
      - kf6-ktextwidgets
      - kf6-kuserfeedback
      - kf6-kwidgetsaddons
      - kf6-kwindowsystem
      - kf6-kxmlgui
      - kf6-syntax-highlighting
      - qt6-base
      - qt6-base-dev
      - qt6-wayland
      - kf6-sonnet
      - exuberant-ctags
      - git
      - khelpcenter
      - konsole-kpart
      - mercurial
      - subversion
      - python3
      - libsecret-1-0
      - patchelf
      - libffi8
    stage-snaps:
      - gtk-theme-breeze
      - icon-theme-breeze
    source: .
    source-type: local
    build-attributes:
      - enable-patchelf
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
      - -DCMAKE_INSTALL_SYSCONFDIR=/etc
      - -DCMAKE_INSTALL_LOCALSTATEDIR=/var
      - -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON
      - -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF
      - -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON
      - -DCMAKE_INSTALL_RUNSTATEDIR=/run
      - -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON
      - -DCMAKE_VERBOSE_MAKEFILE=ON
      - -DCMAKE_INSTALL_LIBDIR=lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - --log-level=STATUS
      - -DCMAKE_LIBRARY_PATH=lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
    build-environment:
    -   PATH: $CRAFT_STAGE/usr/bin:usr/bin${PATH:+:$PATH}
    -   XDG_DATA_DIRS: $CRAFT_STAGE/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
    -   XDG_CONFIG_HOME: $CRAFT_STAGE/etc/xdg:/etc/xdg${XDG_CONFIG_HOME:+:$XDG_CONFIG_HOME}
    -   LD_LIBRARY_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$CRAFT_STAGE/usr/lib:$CRAFT_STAGE/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    -   CMAKE_PREFIX_PATH: $CRAFT_STAGE;/usr${CMAKE_PREFIX_PATH:+;$CMAKE_PREFIX_PATH}
    -   CMAKE_FIND_ROOT_PATH: $CRAFT_STAGE;/usr${CMAKE_FIND_ROOT_PATH:+;$CMAKE_FIND_ROOT_PATH}
    stage:
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri
    prime:
      - "-usr/lib/*/cmake/*"
      - "-usr/include/*"
      - "-usr/share/ECM/*"
      - "-usr/share/man/*"
      - "-usr/bin/X11"
      - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0"
      - "-usr/lib/aspell/*"
      - "-usr/lib/*/dri/*"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsvn_auth_kwallet-1.so.1.0.0"
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libglapi.so.0.0.0
      - -usr/share/doc/libglapi-mesa/changelog.Debian.gz
    override-prime: |
      craftctl default
      patchelf --force-rpath --set-rpath /snap/core24/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri/crocus_dri.so
      patchelf --force-rpath --set-rpath /snap/core24/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri/d3d12_dri.so
      patchelf --force-rpath --set-rpath /snap/core24/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri/i915_dri.so
      patchelf --force-rpath --set-rpath /snap/core24/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri/iris_dri.so
      patchelf --force-rpath --set-rpath /snap/core24/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri/kms_swrast_dri.so
      patchelf --force-rpath --set-rpath /snap/core24/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri/nouveau_dri.so
      patchelf --force-rpath --set-rpath /snap/core24/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri/r300_dri.so
      patchelf --force-rpath --set-rpath /snap/core24/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri/r600_dri.so
      patchelf --force-rpath --set-rpath /snap/core24/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri/radeonsi_dri.so
      patchelf --force-rpath --set-rpath /snap/core24/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri/swrast_dri.so
      patchelf --force-rpath --set-rpath /snap/core24/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri/virtio_gpu_dri.so
      patchelf --force-rpath --set-rpath /snap/core24/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri/vmwgfx_dri.so
      patchelf --force-rpath --set-rpath /snap/core24/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri/zink_dri.so
