---
name: kate
confinement: classic
grade: stable
base: core22
adopt-info: kate
apps:
  kate:
    command: usr/bin/kate
    common-id: org.kde.kate.desktop
    desktop: usr/share/applications/org.kde.kate.desktop
assumes:
  - snapd2.58.3
compression: lzo
environment:
  QTWEBENGINEPROCESS_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt6/libexec/QtWebEngineProcess"
  XDG_CONFIG_DIRS: $SNAP_USER_DATA/.config:$XDG_CONFIG_DIRS
  __EGL_VENDOR_LIBRARY_DIRS: "$SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d"
  LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/${CRAFT_ARCH_TRIPLET}/dri"
  LD_LIBRARY_PATH: ":$SNAP/usr/lib:$SNAP/lib/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio:${LD_LIBRARY_PATH}"
  PATH: $SNAP/usr/bin:${PATH}
  XDG_DATA_DIRS: $SNAP/usr/share:$SNAP_USER_DATA/.local/usr/share:$SNAP/usr/share:$SNAP/data-dir
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins
layout:
  /usr/share/X11:
    symlink: $SNAP/usr/share/X11
  /usr/share/qt6:
    bind: $SNAP/usr/share/qt6
package-repositories:
  - type: apt
    components:
      - main
    suites:
      - jammy
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
  mesa-patchelf:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      - freeglut3
      - libglu1-mesa
    stage:
      - "-usr/lib/${CRAFT_ARCH_TRIPLET}/dri"
  mesa-no-patchelf:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
    build-attributes:
      - no-patchelf
    stage:
      - usr/lib/${CRAFT_ARCH_TRIPLET}/dri
  qtconf:
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      cat <<EOF > $CRAFT_PART_INSTALL/usr/bin/qt.conf
      [Paths]
      Prefix = ../../
      LibraryExecutables = usr/lib/$CRAFT_ARCH_TRIPLET/qt6/libexec
      Plugins = usr/lib/$CRAFT_ARCH_TRIPLET/qt6/plugins
      Qml2Imports = usr/lib/$CRAFT_ARCH_TRIPLET/qt6/qml
      Translations = usr/share/qt6/translations
      Data = usr/share/qt6
      EOF
  kate:
    after:
      - mesa-patchelf
      - mesa-no-patchelf
      - qtconf
    parse-info:
      - usr/share/metainfo/org.kde.kate.appdata.xml
    plugin: cmake
    build-packages:
      - gettext
      - doxygen
      - graphviz
      - libxml2-utils
      - docbook-xml
      - docbook-xsl
      - libglx-dev
      - libgl-dev
      - libglvnd-dev
      - libxkbcommon-dev
      - libpulse0
    stage-packages:
      - darcs
      - exuberant-ctags
      - git
      - mercurial
      - subversion
      - libsecret-1-0
      - ibus
      - ibus-wayland
      - fcitx5
      - fcitx5-modules
      - fcitx-mozc
      - libxkbcommon0
      - libpulse0
      - libjansson4
      - libgif7
      - patchelf
      - samba-libs
      - libpcre3
    source: .
    source-type: local
    build-attributes:
      - enable-patchelf
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
      - -DCMAKE_INSTALL_SYSCONFDIR=/etc
      - -DCMAKE_INSTALL_LOCALSTATEDIR=/var
      - -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON
      - -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF
      - -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON
      - -DCMAKE_INSTALL_RUNSTATEDIR=/run
      - -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON
      - -DCMAKE_VERBOSE_MAKEFILE=ON
      - -DCMAKE_INSTALL_LIBDIR=lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - --log-level=STATUS
      - -DCMAKE_LIBRARY_PATH=lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
    build-environment:
    -   PATH: $CRAFT_STAGE/usr/bin:usr/bin${PATH:+:$PATH}
    -   XDG_DATA_DIRS: $CRAFT_STAGE/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
    -   XDG_CONFIG_HOME: $CRAFT_STAGE/etc/xdg:/etc/xdg${XDG_CONFIG_HOME:+:$XDG_CONFIG_HOME}
    -   LD_LIBRARY_PATH: $CRAFT_STAGE/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:$CRAFT_STAGE/usr/lib:$CRAFT_STAGE/lib/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    -   CMAKE_PREFIX_PATH: $CRAFT_STAGE;/usr${CMAKE_PREFIX_PATH:+;$CMAKE_PREFIX_PATH}
    -   CMAKE_FIND_ROOT_PATH: $CRAFT_STAGE;/usr${CMAKE_FIND_ROOT_PATH:+;$CMAKE_FIND_ROOT_PATH}
    prime:
      - "-usr/lib/*/cmake/*"
      - "-usr/include/*"
      - "-usr/share/ECM/*"
      - "-usr/share/man/*"
      - "-usr/bin/X11"
      - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0"
      - "-usr/lib/aspell/*"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri"
