Import('env')

sources = """
kateautoindent.cpp
katebookmarks.cpp
katebuffer.cpp
katecmd.cpp
katecmds.cpp
katecodecompletion.cpp
katecodefoldinghelpers.cpp
katecompletiondelegate.cpp
katecompletionmodel.cpp
katecompletiontree.cpp
katecompletionwidget.cpp
kateconfig.cpp
katecursor.cpp
katedialogs.cpp
katedocument.cpp
katedocument.skel
katedocumenthelpers.cpp
katedynamicanimation.cpp
kateedit.cpp
kateextendedattribute.cpp
katefactory.cpp
katefiletype.cpp
katefont.cpp
kateglobal.cpp
katehighlight.cpp
kateindentscriptabstracts.cpp
katelayoutcache.cpp
katelinerange.cpp
kateluascript.cpp
kateprinter.cpp
katerange.cpp
katerenderer.cpp
katerenderrange.cpp
kateschema.cpp
katesearch.cpp
katesmartcursor.cpp
katesmartcursornotifier.cpp
katesmartmanager.cpp
katesmartrange.cpp
katesmartregion.cpp
katespell.cpp
katesyntaxdocument.cpp
katetemplatehandler.cpp
katetextlayout.cpp
katetextline.cpp
kateundo.cpp
kateview.cpp
kateviewhelpers.cpp
kateviewinternal.cpp
"""

includes = """
../../interfaces
../../interfaces/kregexpeditor
../../kdeprint
../../kutils
"""

# TODO move this to a more generic place
env['BUILDERS']['Hash']    = Builder(action="perl kjs/create_hash_table $SOURCE -i > $TARGET" ,suffix='.lut.h',src_suffix='.cpp')

for i in ["katejscript.cpp"]:
    env.Hash(i)

libpaths = """
../../interfaces/ktexteditor
../../interfaces/kdocument
../../kparts
../../kdeprint
../../kutils
../../kjs
../../kio
../../dcop
"""

libs = 'ktexteditor kdocument kparts kdeprint kutils kjs kio DCOP'

obj = env.kdeobj('module')
obj.target = 'katepart'
obj.source = sources
obj.includes = includes
obj.libpaths = libpaths
obj.libs = libs
obj.uselib = 'QT QTCORE QTGUI QTXML QT3SUPPORT KDE4 KDECORE KDEUI'
obj.execute()
