#pragma once
#include <QBitArray>
#include <QByteArray>
#include <QCborArray>
#include <QCborMap>
#include <QCborValue>
#include <QDateTime>
#include <QDebug>
#include <QMetaObject>
#include <QObject>
#include <QString>
#include <QStringList>
#include <QThread>
#include <QtCborCommon>
#include <QtGlobal>
#include <algorithm>
#include <atomic>
#include <future>
#include <semaphore>
#include <thread>
#include <type_traits>
