#ifndef KTEXTEDITOR_CODESNIPPETS_CORE_EXPORT_H
#define KTEXTEDITOR_CODESNIPPETS_CORE_EXPORT_H

/* needed for KDE_EXPORT macros */
#include <kdemacros.h>

#ifdef KTEXTEDITOR_CODESNIPPETS_CORE_LIB
# define KTEXTEDITOR_CODESNIPPETS_CORE_EXPORT KDE_EXPORT
#else
# ifdef Q_OS_WIN
#  define KTEXTEDITOR_CODESNIPPETS_CORE_EXPORT KDE_IMPORT
# else
#  define KTEXTEDITOR_CODESNIPPETS_CORE_EXPORT KDE_EXPORT
# endif
#endif

#endif